// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class contact_date_and_messageAdd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(contact_date_and_messageAdd));
        
        string IMigrationMetadata.Id
        {
            get { return "202208091217175_contact_date_and_messageAdd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
