// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class about_image_lenght : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(about_image_lenght));
        
        string IMigrationMetadata.Id
        {
            get { return "202208090819449_about_image_lenght"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
